import {AREAS,missionKey,makeQuestions,newRun,answer,advance,summary,mergeRun} from './engine.mjs';
import {Cloud,friendlyError} from './cloud.mjs';
const QA=window.self!==window.top&&new URL(location.href).searchParams.get('qa')==='1';
const KEY=QA?'liam-dagmissie-qa-v3':'liam-dagmissie-v3';
const SESSION_KEY=QA?'liam-dagmissie-qa-session-v2':'liam-dagmissie-session-v2';
const $=id=>document.getElementById(id);
const cloud=new Cloud(SESSION_KEY);
let state=load(), view='home',selected=null,authMode='login',syncing=false,syncAgain=false,storageOk=true,toastTimer;
function load(){try{const current=JSON.parse(localStorage.getItem(KEY));if(current?.version===3&&Array.isArray(current.runs))return current;const old=JSON.parse(localStorage.getItem(QA?'liam-dagmissie-qa-v2':'liam-dagmissie-v2'));return old?.version===2&&Array.isArray(old.runs)?{version:3,runs:old.runs,activeId:old.activeId}:{version:3,runs:[],activeId:null};}catch{return {version:3,runs:[],activeId:null};}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOk=true;}catch{storageOk=false;}storageStatus();}
function visibleRuns(){return state.runs.filter(r=>!r.ownerId||r.ownerId===cloud.session?.user?.id);}
function active(){return visibleRuns().find(r=>r.id===state.activeId);}
function dateLabel(date){return new Intl.DateTimeFormat('nl-BE',{timeZone:'Europe/Brussels',weekday:'long',day:'numeric',month:'long'}).format(new Date(date+'T12:00:00Z'));}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function show(which,focus=true){view=which;for(const name of ['home','quiz','result','history'])$(name+'-view').classList.toggle('hidden',name!==which);window.scrollTo({top:0,behavior:'instant'});if(focus)$('main').focus({preventScroll:true});}
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),5000);}
function storageStatus(){
  if(!storageOk){$('storage-status').textContent='Opslaan op dit toestel lukt niet. Houd dit tabblad open.';return;}
  const unsynced=visibleRuns().some(r=>!r.synced);
  $('storage-status').textContent=cloud.session?(syncing?'Op dit toestel bewaard · resultaten koppelen…':unsynced?'Op dit toestel bewaard · koppeling volgt bij verbinding':'Op dit toestel én in je ouderaccount bewaard'):'Op dit toestel bewaard · aanmelden is optioneel';
}
function renderHome(){const today=missionKey();$('date-label').textContent=dateLabel(today);$('mission-title').textContent=makeQuestions(today).title;const run=active()?.date===today?active():null,todayRuns=visibleRuns().filter(r=>r.date===today&&r.finished);const first=todayRuns.slice().sort((a,b)=>a.startedAt.localeCompare(b.startedAt))[0];$('start-button').textContent=run&&!run.finished&&!run.abandoned?'Verder met mijn missie →':todayRuns.length?'Nog eens oefenen →':'Start mijn dagmissie →';$('stats-text').textContent=todayRuns.length?`Vandaag ${todayRuns.length} ${todayRuns.length===1?'missie':'missies'} voltooid · eerste score ${summary(first).score}/${first.questions.length}.`:run&&!run.finished&&!run.abandoned?`${run.answers.filter(Boolean).length} van ${run.questions.length} antwoorden bewaard. Ga verder wanneer je wil.`:'Elke dag een beetje slimmer.';storageStatus();}
function start(force=false){const today=missionKey();let r=active();if(force||!r||r.finished||r.abandoned||r.date!==today){const attempt=1+Math.max(0,...visibleRuns().filter(x=>x.date===today).map(x=>x.attempt));r=newRun(today,attempt);r.ownerId=cloud.session?.user?.id||null;state.runs.push(r);state.activeId=r.id;save();queueSync();}selected=null;show('quiz');renderQuestion();}
function home(){selected=null;show('home');renderHome();}
function renderQuestion(){const run=active();if(!run){home();return;}if(run.finished){renderResult(run);return;}const q=run.questions[run.index],saved=run.answers[run.index],area=AREAS[q.area];$('question-area').className='area-tag '+area.color;$('question-area').textContent=area.name;$('quiz-counter').textContent=`Vraag ${run.index+1} van ${run.questions.length}`;const count=run.answers.filter(Boolean).length;$('progress-value').style.width=(count/run.questions.length*100)+'%';$('progress').setAttribute('aria-valuemax',run.questions.length);$('progress').setAttribute('aria-valuenow',count);const content=$('question-content');content.replaceChildren();if(q.passage){const passage=el('div','passage');passage.append(el('span','story-title',q.storyTitle),el('span','',q.passage));content.append(passage);}const title=el('h2','question-title',q.prompt);content.append(title);if(q.chunks)content.append(el('div','chunks',q.chunks));const options=$('answer-options');options.replaceChildren();q.options.forEach((value,i)=>{const b=el('button','answer');b.type='button';b.append(el('span','answer-key',saved?(saved.value===value?(saved.correct?'✓':'×'):value===q.correct?'✓':String.fromCharCode(65+i)):String.fromCharCode(65+i)),el('span','answer-text',value));b.setAttribute('aria-pressed',String((saved?.value||selected)===value));b.disabled=!!saved;if(saved){if(value===q.correct)b.classList.add('correct');if(saved.value===value&&!saved.correct)b.classList.add('wrong');}else if(value===selected)b.classList.add('selected');b.addEventListener('click',()=>{if(active().answers[active().index])return;selected=value;renderQuestion();$('answer-options').children[i].focus({preventScroll:true});});options.append(b);});$('confirm-button').classList.toggle('hidden',!!saved);$('confirm-button').disabled=selected===null;$('next-button').classList.toggle('hidden',!saved);$('next-button').textContent=run.index===run.questions.length-1?'Bekijk mijn eindscore →':'Volgende vraag →';$('question-hint').textContent=saved?'Je antwoord staat vast. Goed gewerkt!':'Kies een antwoord. Bevestig als je zeker bent.';const feedback=$('feedback');feedback.className=saved?'feedback '+(saved.correct?'good':'try'):'hidden';feedback.replaceChildren();if(saved){feedback.append(el('strong','',saved.correct?'✓ Helemaal juist!':'✦ Dit was niet juist. Je leert het!'),el('small','',saved.correct?q.explanation:`Het juiste antwoord is: ${q.correct}. ${q.explanation}`));}}
function confirm(){const r=active();if(!r||selected===null||!answer(r,selected))return;selected=null;save();renderQuestion();$('next-button').focus({preventScroll:true});queueSync();}
function next(){const r=active();if(!r||!advance(r))return;selected=null;save();if(r.finished)renderResult(r);else{renderQuestion();window.scrollTo({top:0,behavior:'instant'});const t=$('question-content').querySelector('h2');t.tabIndex=-1;t.focus({preventScroll:true});}queueSync();}
function renderResult(r){show('result');const s=summary(r),panel=el('div','result-panel');panel.append(el('div','result-top','✦'),el('div','eyebrow','JOUW DAGMISSIE IS VOLBRACHT'),el('h1','',s.score===s.total?'Alles fonkelt!':'Goed geoefend, Liam!'));const circle=el('div','score-circle');circle.append(el('strong','',String(s.score)),el('span','',`van de ${s.total} juist`));panel.append(circle,el('p','result-message',s.score/s.total>=.75?'Wat een knappe missie! Je hebt je hoofd goed laten werken.':'Elke poging maakt je een beetje sterker. Goed dat je hebt geoefend!'));const subjects=el('div','subject-results');for(const [key,counts]of Object.entries(s.by).filter(([,counts])=>counts.total)){const item=el('div','subject-result');item.append(el('strong','',AREAS[key].name),el('span','',`${counts.correct} / ${counts.total}`));subjects.append(item);}panel.append(subjects);const actions=el('div','result-actions'),homeBtn=el('button','primary','Naar home →'),again=el('button','secondary','Opnieuw oefenen'),history=el('button','secondary','Mijn resultaten');homeBtn.onclick=home;again.onclick=()=>start(true);history.onclick=renderHistory;actions.append(homeBtn,again,history);panel.append(actions,el('p','saved-note',`Poging ${r.attempt} · ${dateLabel(r.date)} · ${storageOk?'Je score is bewaard op dit toestel.':'Opslaan op dit toestel lukt niet.'}`));const review=el('details','review');review.append(el('summary','','Bekijk je antwoorden'));r.questions.forEach((q,i)=>{const a=r.answers[i],item=el('div','review-item');item.append(el('strong','',`${i+1}. ${q.prompt}`),el('div','',`${a?.correct?'✓':'✦'} Jouw antwoord: ${a?.value||'Geen antwoord'}`),el('p','',a?.correct?q.explanation:`Juist antwoord: ${q.correct}. ${q.explanation}`));review.append(item);});panel.append(review);$('result-view').replaceChildren(panel);}
function renderHistory(){show('history');const list=$('history-list');list.replaceChildren();const runs=visibleRuns().slice().sort((a,b)=>b.startedAt.localeCompare(a.startedAt));if(!runs.length){list.append(el('p','empty-history','Je eerste avontuur wacht op je. Start een dagmissie!'));return;}for(const r of runs){const s=summary(r),item=el('div','history-item'),copy=el('div');item.append(el('span','history-score',r.finished?`${s.score}/${s.total}`:'…'));copy.append(el('h3','',r.title),el('p','',`${dateLabel(r.date)} · poging ${r.attempt}${r.attempt===1?' · eerste poging':''}`),el('p','',r.finished?(r.synced?'Voltooid · gekoppeld aan ouderaccount':'Voltooid · op dit toestel bewaard'):r.abandoned?'Gestopt bij een nieuwe start · antwoorden bewaard':`${r.answers.filter(Boolean).length} antwoorden · gepauzeerd`));item.append(copy);if(r.finished||!r.abandoned){const b=el('button','text-button',r.finished?'Bekijk →':'Verder →');b.onclick=()=>{state.activeId=r.id;selected=null;save();if(r.finished)renderResult(r);else{show('quiz');renderQuestion();}};item.append(b);}list.append(item);}}
function reset(){const r=active();if(r){r.abandoned=true;r.synced=false;}save();$('reset-dialog').close();start(true);}
function renderAccount(){const signed=!!cloud.session;$('account-label').textContent=signed?'Ouderaccount':'Aanmelden';$('signed-out-panel').classList.toggle('hidden',signed);$('signed-in-panel').classList.toggle('hidden',!signed);if(signed){$('account-email').textContent=cloud.session.user.email;$('sync-info').textContent='Je resultaten worden automatisch gekoppeld. Ook eerdere gastpogingen op dit toestel gaan mee.';}storageStatus();}
function mode(value){authMode=value;$('login-tab').classList.toggle('active',value==='login');$('signup-tab').classList.toggle('active',value==='signup');$('auth-submit').textContent=value==='signup'?'Ouderaccount maken':'Aanmelden';$('password').autocomplete=value==='signup'?'new-password':'current-password';$('password').minLength=value==='signup'?8:1;$('password').placeholder=value==='signup'?'Minstens 8 tekens':'Je wachtwoord';$('auth-message').textContent='';}
async function submitAuth(event){event.preventDefault();const submit=$('auth-submit');submit.disabled=true;submit.textContent='Even wachten…';$('auth-message').textContent='';try{const data=authMode==='login'?await cloud.login($('email').value.trim(),$('password').value):await cloud.signup($('email').value.trim(),$('password').value);$('password').value='';if(data.access_token){renderAccount();$('account-dialog').close();toast('Aangemeld. Je bewaarde resultaten worden gekoppeld.');await syncAll();}else{$('auth-message').className='success';$('auth-message').textContent='Controleer je mailbox en bevestig je e-mailadres. Kom daarna terug en meld je aan. Oefenen kan intussen zonder account.';}}catch(error){$('auth-message').className='';$('auth-message').textContent=friendlyError(error);}finally{submit.disabled=false;submit.textContent=authMode==='signup'?'Ouderaccount maken':'Aanmelden';}}
function queueSync(){if(!cloud.session)return;void syncAll();}
async function syncAll(){if(!cloud.session)return;if(syncing){syncAgain=true;return;}syncing=true;storageStatus();const button=$('sync-button');button.disabled=true;try{const records=await cloud.listRuns();for(const record of records){const remote=record.progress?.run;if(![2,3].includes(remote?.version))continue;const i=state.runs.findIndex(r=>r.id===remote.id);if(i<0)state.runs.push({...remote,ownerId:cloud.session.user.id,synced:true});else state.runs[i]={...mergeRun(state.runs[i],remote),ownerId:cloud.session.user.id,synced:state.runs[i].synced};}for(const r of visibleRuns().filter(r=>!r.synced)){const snapshot=structuredClone(r);const synced=await cloud.syncRun(snapshot);const i=state.runs.findIndex(x=>x.id===r.id);const latest=state.runs[i];const merged=mergeRun(latest,synced);const changed=JSON.stringify({...latest,synced:undefined,ownerId:undefined})!==JSON.stringify({...snapshot,synced:undefined,ownerId:undefined});state.runs[i]={...merged,ownerId:cloud.session.user.id,synced:!changed};if(changed)syncAgain=true;}if(!active()){const resumable=visibleRuns().filter(r=>!r.finished&&!r.abandoned&&r.date===missionKey()).sort((a,b)=>b.startedAt.localeCompare(a.startedAt))[0];if(resumable)state.activeId=resumable.id;}save();if(view==='home')renderHome();if(view==='history')renderHistory();if(view==='quiz')renderQuestion();$('sync-info').textContent='Je resultaten zijn bijgewerkt in je ouderaccount.';}catch(error){$('sync-info').textContent=friendlyError(error);toast('Je voortgang blijft op dit toestel bewaard. Koppelen lukt nu niet; we proberen opnieuw zodra je verbinding hebt.');}finally{syncing=false;button.disabled=false;$('account-label').textContent=cloud.session?'Ouderaccount':'Aanmelden';storageStatus();if(syncAgain){syncAgain=false;queueSync();}}}
$('start-button').onclick=()=>start();$('brand-home').onclick=home;$('home-button').onclick=home;$('history-home').onclick=home;$('history-button').onclick=renderHistory;$('confirm-button').onclick=confirm;$('next-button').onclick=next;$('reset-button').onclick=()=>$('reset-dialog').showModal();$('reset-confirm').onclick=reset;$('account-button').onclick=()=>{renderAccount();$('account-dialog').showModal();};$('login-tab').onclick=()=>mode('login');$('signup-tab').onclick=()=>mode('signup');$('auth-form').onsubmit=submitAuth;$('sync-button').onclick=syncAll;$('logout-button').onclick=async()=>{try{await cloud.logout();}catch{}state.activeId=null;selected=null;save();renderAccount();$('account-dialog').close();home();toast('Afgemeld. Je kunt zonder account verder oefenen.');};document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',event=>{if(event.target===d){const rect=d.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)d.close();}}));window.addEventListener('online',queueSync);
window.addEventListener('storage',event=>{if(event.key===KEY&&event.newValue){state=load();selected=null;if(view==='quiz')renderQuestion();else if(view==='home')renderHome();else if(view==='history')renderHistory();}if(event.key===SESSION_KEY){try{cloud.session=JSON.parse(event.newValue);}catch{cloud.session=null;}renderAccount();}});
const r=active();if(r?.date!==missionKey())state.activeId=null;
renderAccount();home();save();
if(cloud.session)void cloud.validate().then(()=>{renderAccount();queueSync();}).catch(()=>renderAccount());
